{{- if and .Values.global.dbtPipeline.enabled .Values.dbtPipeline.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lago-data.fullname" . }}-dbt-pipeline
  labels:
    {{- include "lago-data.labels" . | nindent 4 }}
    app.kubernetes.io/component: dbt-pipeline
  {{- with .Values.dbtPipeline.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.dbtPipeline.serviceAccount.automount }}
{{- end }}
