{{- if .Values.configs.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data.secretName" . }}
  labels:
    {{- include "lago-data.labels" (dict "context" . "component" .Values.api.name "name" "secret") | nindent 4 }}
    {{- with .Values.configs.secret.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configs.secret.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  {{- include "lago-data.configs.secret" . | trim | nindent 2 }}
{{- end }}
