{{- if not .Values.config.databaseAnalytical.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lago-data-forecasted-usage.fullname" . }}-analytical-db
  labels:
    {{- include "lago-data-forecasted-usage.labels" . | nindent 4 }}
data:
  databaseAnalytical.host: {{ .Values.config.databaseAnalytical.host }}
  {{- with .Values.config.databaseAnalytical.name }}
  databaseAnalytical.name: {{ . }}
  {{- end }}
  {{- with .Values.config.databaseAnalytical.port }}
  databaseAnalytical.port: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.databaseAnalytical.schema }}
  databaseAnalytical.schema: {{ . }}
  {{- end }}
{{- end }}
