apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: # https://vault.example.com
      path: # secret
      version: v2
      auth:
        kubernetes:
          mountPath: # kubernetes
          role: # lago
          serviceAccountRef:
            name: # lago
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lago-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: lago-config
    creationPolicy: Owner
  data:
    - secretKey: database.uri
      remoteRef:
        key: secret/data/lago/database
        property: uri

    - secretKey: encryption.key
      remoteRef:
        key: secret/data/lago/encryption
        property: key

    - secretKey: encryption.salt
      remoteRef:
        key: secret/data/lago/encryption
        property: salt

    - secretKey: signing.hmac
      remoteRef:
        key: secret/data/lago/signing
        property: hmac

    - secretKey: signing.rsa
      remoteRef:
        key: secret/data/lago/signing
        property: rsa

    # - secretKey: redis.password
    #   remoteRef:
    #     key: secret/data/lago/redis
    #     property: password

    # - secretKey: redisCache.password
    #   remoteRef:
    #     key: secret/data/lago/redis-cache
    #     property: password

    # - secretKey: redisStore.password
    #   remoteRef:
    #     key: secret/data/lago/redis-store
    #     property: password

    - secretKey: lago.license
      remoteRef:
        key: secret/data/lago/license
        property: key

    - secretKey: s3.accessKeyId
      remoteRef:
        key: secret/data/lago/s3
        property: accessKeyId

    - secretKey: s3.secretAccessKey
      remoteRef:
        key: secret/data/lago/s3
        property: secretAccessKey
