global:
  ago:
    env: "production"
    license: ""
    signup: false
    cloud: false
    sidekiqPro: false
    pdfGeneration: false

  config:
    configmap:
    secret:

  urls:
    api: ""
    front: ""
    pdf: ""

  database:
    uri: ""
    pool: 20

  encryption:
    key: "" # ENCRYPTION_PRIMARY_KEY
    salt: "" # ENCRYPTION_KEY_DERIVATION_SALT

  signing:
    hmac: "" # SECRET_KEY_BASE used by webhooks, message verifier HS256
    rsa: ""  # LAGO_RSA_PRIVATE_KEY used by webhooks RS256

  redis:
    url: ""
    password: ""

  redisCache:
    url: ""
    password: ""

  redisStore:
    url: ""
    password: ""

  sentryDsn: ""

  databaseAnalytical:
    host: ""
    name: ""
    user: ""
    password: ""
    port: 5432
    schema: analytical

  forecasted_usage:
    enabled: false
    # forecasted usage need to call lago-api, hence provide a valid token
    api_token:
    celery:
      brokerUrl: ""
      resultBackend: ""

  data:
    configmap:
    secret:
    # token to validate calls from lago-api
    token:

api:
  fullnameOverride: lago-api
  config:
    enabled: false

  extraEnv:
    - name: LAGO_DATA_API_BEARER_TOKEN
      valueFrom:
        secretKeyRef:
          name: lago-data-config
          key: api.token

data-api:
  fullnameOverride: lago-data-api
  config:
    enabled: false
    api:
      url: lago-api # this is the value of the api.fullnameOverride


data-worker:
  fullnameOverride: lago-data-worker
  config:
    enabled: false
    api:
      url: http://lago-api

celery-exporter:
  enabled: true
  env:
    - name: CE_BROKER_URL
      valueFrom:
        configMapKeyRef:
          name: lago-data-config
          key: celery.brokerUrl

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  podAnnotations:
    prometheus.io/scrape: "true"
