apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lago-data-config.configMapName" . }}
  labels:
    {{- include "lago-data-config.labels" . | nindent 4 }}
    {{- with .Values.configmap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configmap.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  databaseAnalytical.host: {{ required "global.databaseAnalytical.host is required" .Values.global.databaseAnalytical.host }}
  {{- with .Values.global.databaseAnalytical.name }}
  databaseAnalytical.name: {{ . }}
  {{- end }}
  databaseAnalytical.user: {{ .Values.global.databaseAnalytical.user }}
  {{- with .Values.global.databaseAnalytical.port }}
  databaseAnalytical.port: {{ quote . }}
  {{- end }}
  {{- with .Values.global.databaseAnalytical.schema }}
  databaseAnalytical.schema: {{ . }}
  {{- end }}
  {{- if .Values.global.forecasted_usage.enabled }}
  celery.brokerUrl: {{ required "global.celery.brokerUrl is required" .Values.global.celery.brokerUrl }}
  celery.resultBackend: {{ required "global.celery.resultBackend is required" .Values.global.celery.resultBackend }}
  {{- end }}
