{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data-config.secretName" . }}
  labels:
    {{- include "lago-data-config.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  bearer: {{ required "global.data.token is required" .Values.global.data.token | b64enc}}
  {{- if .Values.global.forecasted_usage.enabled }}
  api.token: {{ required "global.forecasted_usage.api_token is required" .Values.global.forecasted_usage.api_token | b64enc}}
  databaseAnalytical.password: {{ b64enc .Values.global.databaseAnalytical.password }}
  {{- end }}

{{- end }}
