apiUrl: "api.lago.dev"
frontUrl: "front.lago.dev"

global:
  databaseUrl: postgres://postgres:postgres@postgres:5432/postgres
  redisUrl: redis://redis:6379

job:
  migrate:
    loadSchema: true

api:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"
worker:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

eventsWorker:
  enabled: false

clockWorker:
  enabled: false

pdf:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

billingWorker:
  enabled: false

pdfWorker:
  enabled: false

webhookWorker:
  enabled: false

paymentWorker:
  enabled: false
