apiVersion: v2
name: lago-pdf
description: A Helm chart for the Lago PDF stack (Gotenberg + optional Rails worker)

type: application

version: 0.14.0

appVersion: "8.32"

dependencies:
  - name: lago-config
    alias: config
    version: 0.14.0
    repository: "file://../lago-config"
    condition: config.enabled
  - name: lago-rails
    alias: worker
    version: 0.14.0
    repository: "file://../lago-rails"
    condition: worker.enabled

annotations:
  org.opencontainers.image.source: "https://github.com/getlago/lago-helm-charts"
