# Default values for lago-events-processor-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values shared across all subcharts
global:
  lago:
    env: "production"

  config:
    secret: ""
    configmap: ""

  database:
    uri: ""

  redisCache:
    url: ""
    password: ""

  redisStore:
    url: ""
    password: ""

  streaming_ingestion:
    enabled: true
    configmap: ""
    secret: ""

    # kafka is required if clickhouse is set
    kafka:
      # username and password are not required here if if using an external secret:
      #  config.enabled: false, config.secret.name: "..."
      username: ""
      password: ""
      tls: false
      # SCRAM-SHA-512, SCRAM-SHA-256
      saslMechanisms:
      consumerGroup: events_consumer
      # you must provide a list of Kafka servers if clickhouse is enabled
      bootstrapServers: []
      #   - "kafka-server:9092"
      topics:
        eventsChargedInAdvance: events_charged_in_advance
        eventsDeadLetter: events_dead_letter
        eventsEnriched: events_enriched
        eventsEnrichedExpanded: events_enriched_expanded
        eventsRaw: events_raw
        activityLogs: activity_logs
        apiLogs: api_logs

# Local config specific to this chart instance
config:
  enabled: true
  log:
    level: info

  database:
    pool: 10

  otel:
    enabled: false
    endpoint:
    serviceName:
    tracesSamplerArg:
    tracesSampler:

container:
  name: ""
  command: ["./event_processors"]
  args: []

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: getlago/lago-events-processor
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Environment variables to pass to the api container
extraEnv: []
  # - name: "MY_VAR"
  #   value: "value"

# -- envFrom to pass to the api container
# @default -- `[]` (See [values.yaml])
extraEnvFrom: []
  # - configMapRef:
  #     name: config-map-name
  # - secretRef:
  #     name: secret-name

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  external: false  # Set to true when using external autoscaler (e.g., KEDA)
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

# -- Array of extra K8s manifests to deploy
## Note: Supports use of custom Helm templates
extraObjects: []
  # - |-
  #   apiVersion: networking.k8s.io/v1
  #   kind: Ingress
  #   metadata:
  #     annotations:
  #       nginx.ingress.kubernetes.io/backend-protocol: HTTP
  #       nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #       nginx.ingress.kubernetes.io/proxy-body-size: 50m
  #       nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
  #       nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
  #       nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
  #     labels:
  #       {{- include "lago-events-processor-worker.labels" . | nindent 4 }}
  #     name: {{ include "lago-events-processor-worker.fullname" . }}-webhooks-internal
  #   spec:
  #     ingressClassName: nginx
  #     rules:
  #     - host: webhooks.internal.getlago.com
  #       http:
  #         paths:
  #         - backend:
  #             service:
  #               name: {{ include "lago-events-processor-worker.fullname" . }}
  #               port:
  #                 number: 80
  #           path: /webhooks
  #           pathType: Prefix
  #     tls:
  #     - hosts:
  #       - webhooks.internal.getlago.com
  #       secretName: webhook-cert-tls
