apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.lago.service: {{ .Release.Name }}-api
  name: {{.Release.Name}}-api-svc
spec:
  ports:
    - name: "api"
      port: {{ .Values.api.service.port }}
      targetPort: 3000
  selector:
    io.lago.service: {{ .Release.Name }}-api
