apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    {{ include "lago.api.labels" . | nindent 4 }}
  name: {{.Release.Name}}-api-svc
spec:
  ports:
    - name: "api"
      port: {{ .Values.api.service.port }}
      targetPort: 3000
  selector:
    {{ include "lago.api.selectorLabels" . | nindent 4 }}
