apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    {{ include "lago.pdf.labels" . | nindent 4 }}
  name: {{ .Release.Name}}-pdf-svc
spec:
  ports:
    - name: "pdf"
      port: {{ .Values.pdf.service.port }}
      targetPort: 3000
  selector:
    {{ include "lago.pdf.selectorLabels" . | nindent 4 }}
