apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago-data-api.fullname" . }}
  labels:
    {{- include "lago-data-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lago-data-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lago-data-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lago-data-api.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ default .Chart.Name .Values.container.name }}
          command: {{ toJson .Values.container.command }}
          args: {{ toJson .Values.container.args }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.ports.http }}
              protocol: TCP
          envFrom:
            {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: ANALYTICAL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lago-data-config.configMapName" . }}
                  key: databaseAnalytical.host
            - name: ANALYTICAL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lago-data-config.configMapName" . }}
                  key: databaseAnalytical.name
            - name: ANALYTICAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "lago-data-config.secretName" . }}
                  key: databaseAnalytical.password
            - name: ANALYTICAL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lago-data-config.configMapName" . }}
                  key: databaseAnalytical.port
            - name: ANALYTICAL_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lago-data-config.configMapName" . }}
                  key: databaseAnalytical.schema
            - name: ANALYTICAL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lago-data-config.configMapName" . }}
                  key: databaseAnalytical.user
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "lago-data-config.secretName" . }}
                  key: bearer
            {{- if .Values.global.forecasted_usage.enabled }}
            - name: LAGO_RAILS_API_URL
              value: {{ required "global.urls.api must be provided " .Values.global.urls.api }}
            - name: LAGO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "lago-data-config.secretName" . }}
                  key: api.token
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lago-data-config.configMapName" . }}
                  key: celery.brokerUrl
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lago-data-config.configMapName" . }}
                  key: celery.resultBackend
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end}}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
