{{- define "lago-rails.hpa" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lago-rails.architecture.fullname" . }}
  labels:
    {{- include "lago-rails.architecture.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lago-rails.architecture.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

{{- if and .Values.autoscaling.enabled (not .Values.autoscaling.external) }}
{{- $amd64Values := deepCopy .Values }}
{{- $amd64Context := dict "Values" $amd64Values "Chart" .Chart "Release" .Release "Capabilities" .Capabilities "Template" .Template "Files" .Files }}
{{ include "lago-rails.hpa" $amd64Context }}
{{- end }}
{{- $arm64 := .Values.architectures.arm64 }}
{{- if and .Values.global.architectures.arm64.enabled $arm64.autoscaling.enabled (not $arm64.autoscaling.external) }}
---
{{- $arm64Values := deepCopy .Values }}
{{- $_ := set $arm64Values "internalArchitecture" "arm64" }}
{{- $_ := set $arm64Values "internalArchitectureFullname" (include "lago-rails.fullname" .) }}
{{- $_ := set $arm64Values "internalArchitectureName" (include "lago-rails.name" .) }}
{{- $_ := set $arm64Values "autoscaling" $arm64.autoscaling }}
{{- $arm64Context := dict "Values" $arm64Values "Chart" .Chart "Release" .Release "Capabilities" .Capabilities "Template" .Template "Files" .Files }}
{{ include "lago-rails.hpa" $arm64Context }}
{{- end }}
