{{- define "lago-rails.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lago-rails.architecture.fullname" . }}
  labels:
    {{- include "lago-rails.architecture.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lago-rails.architecture.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.service.enabled }}
{{- $amd64Values := deepCopy .Values }}
{{- $amd64Context := dict "Values" $amd64Values "Chart" .Chart "Release" .Release "Capabilities" .Capabilities "Template" .Template "Files" .Files }}
{{ include "lago-rails.service" $amd64Context }}
{{- $arm64 := .Values.architectures.arm64 }}
{{- if and .Values.global.architectures.arm64.enabled (or (gt (int $arm64.replicaCount) 0) $arm64.autoscaling.enabled) }}
---
{{- $arm64Values := deepCopy .Values }}
{{- $_ := set $arm64Values "internalArchitecture" "arm64" }}
{{- $_ := set $arm64Values "internalArchitectureFullname" (include "lago-rails.fullname" .) }}
{{- $_ := set $arm64Values "internalArchitectureName" (include "lago-rails.name" .) }}
{{- $arm64Context := dict "Values" $arm64Values "Chart" .Chart "Release" .Release "Capabilities" .Capabilities "Template" .Template "Files" .Files }}
{{ include "lago-rails.service" $arm64Context }}
{{- end }}
{{- end }}
