{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-config.secretName" . }}
  labels:
    {{- include "lago-config.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  database.uri: {{ required  "global.database.uri value is required" .Values.global.database.uri | b64enc }}
  encryption.key: {{ required  "global.encryption.key value is required" .Values.global.encryption.key | b64enc }}
  encryption.salt: {{ required  "global.encryption.salt value is required" .Values.global.encryption.salt | b64enc }}
  signing.hmac: {{ required  "global.signing.hmac value is required" .Values.global.signing.hmac | b64enc }}
  signing.rsa: {{ required  "global.signing.rsa value is required" .Values.global.signing.rsa | b64enc }}
  {{- with .Values.global.redis.password }}
  redis.password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.redisCache.password }}
  redisCache.password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.redisStore.password }}
  redisStore.password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.lago.license }}
  lago.license: {{ . | b64enc }}
  {{- end }}
  {{- range $name, $dsn := .Values.global.sentry.dsn }}
  {{- if $dsn }}
  sentry.dsn.{{ $name }}: {{ $dsn | b64enc }}
  {{- end }}
  {{- end }}
  {{- with .Values.global.segmentWriteKey }}
  segmentWriteKey: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.nango.secretKey }}
  nango.secretKey: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.nango.publicKey }}
  nango.publicKey: {{ . | b64enc }}
  {{- end }}
  {{- if .Values.global.google.enabled }}
  google.clientId: {{ required "global.google.clientId is required" .Values.global.google.clientId | b64enc }}
  google.clientSecret: {{ required "global.google.clientSecret is required" .Values.global.google.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.global.gocardless.enabled }}
  gocardless.clientId: {{ required "global.gocardless.clientId is required" .Values.global.gocardless.clientId | b64enc }}
  gocardless.clientSecret: {{ required "global.gocardless.clientSecret is required" .Values.global.gocardless.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.global.s3.enabled }}
  {{- with .Values.global.s3.accessKeyId }}
  s3.accessKeyId: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.s3.secretAccessKey }}
  s3.secretAccessKey: {{ . | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.global.mcp.enabled }}
  mcp.clientId: {{ required "global.mcp.clientId is required" .Values.global.mcp.clientId | b64enc }}
  mcp.clientSecret: {{ required "global.mcp.clientSecret is required" .Values.global.mcp.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.global.data.enabled }}
  data.token: {{ required "global.data.token is required" .Values.global.data.token | b64enc }}
  {{- end }}
{{- end }}
