{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-config.secretName" . }}
  labels:
    {{- include "lago-config.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  database.url: {{ b64enc .Values.database.url }}
  encryption.key: {{ b64enc .Values.encryption.key }}
  encryption.salt: {{ b64enc .Values.encryption.salt }}
  signing.hmac: {{ b64enc .Values.signing.hmac }}
  signing.rsa: {{ b64enc .Values.signing.rsa }}
  {{- with .Values.redis.password }}
  redis.password: {{ b64enc . }}
  {{- end }}
  {{- with .Values.redisCache.password }}
  redisCache.password: {{ b64enc . }}
  {{- end }}
  {{- with .Values.redisStore.password }}
  redisStore.password: {{ b64enc . }}
  {{- end }}
  {{- with .Values.lago.license }}
  lago.license: {{.}}
  {{- end }}
{{- end }}
