{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-config.secretName" . }}
  labels:
    {{- include "lago-config.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  database.url: {{ .Values.global.database.url | b64enc }}
  encryption.key: {{ .Values.global.encryption.key | b64enc }}
  encryption.salt: {{ .Values.global.encryption.salt | b64enc }}
  signing.hmac: {{ .Values.global.signing.hmac | b64enc }}
  signing.rsa: {{ .Values.global.signing.rsa | b64enc }}
  {{- with .Values.global.redis.password }}
  redis.password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.redisCache.password }}
  redisCache.password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.redisStore.password }}
  redisStore.password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.lago.license }}
  lago.license: {{ . | b64enc }}
  {{- end }}
  {{- if .Values.global.s3.enabled }}
  {{- with .Values.global.s3.accessKeyId }}
  s3.accessKeyId: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.global.s3.secretAccessKey }}
  s3.secretAccessKey: {{ . | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
