{{- if and .Values.global.streaming_ingestion.enabled .Values.secretStreaming.create }}
{{- $kafka := .Values.global.streaming_ingestion.kafka -}}
{{- $clickhouse := .Values.global.streaming_ingestion.clickhouse -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-config.streaming.secretName" . }}
  labels:
    {{- include "lago-config.labels" . | nindent 4 }}
    {{- with .Values.secretStreaming.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secretStreaming.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{- with $kafka.password }}
  LAGO_KAFKA_PASSWORD: {{ . }}
  {{- end }}
  {{- with $kafka.username }}
  LAGO_KAFKA_USERNAME: {{ . }}
  {{- end }}
  {{- with $clickhouse.username }}
  LAGO_CLICKHOUSE_USERNAME: {{ . }}
  {{- end }}
  {{- with $clickhouse.password }}
  LAGO_CLICKHOUSE_PASSWORD: {{ . }}
  {{- end }}
{{- end }}
