apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas.api }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
        app_revision: {{ .Release.Name }}_{{ .Release.Revision }}_api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app_revision
                    operator: In
                    values:
                      - {{ .Release.Name }}_{{ .Release.Revision }}_api
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: api
          image: getlago/api:v{{ .Values.lago_release }}
          imagePullPolicy: Always
          command: ["./scripts/start.sh"]
          env:
            {{- toYaml .Values.api.environment | nindent 12 }}
          ports:
            - containerPort: {{ .Values.api.port }}
              protocol: TCP
              name: "api"
          resources:
            requests:
              memory: {{ .Values.api.resources.memory }}
              cpu: {{ .Values.api.resources.cpu }}
