apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-svc
spec:
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: api
  selector:
    app: {{ .Release.Name }}-api
