{{- if .Values.postgresql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.lago.service: {{ .Release.Name }}-postgresql
  name: {{ .Release.Name }}-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.lago.service: {{ .Release.Name }}-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.lago.network/lago-default: "true"
        io.lago.service: {{ .Release.Name }}-postgresql
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/postgres
            - name: PGPORT
              value: "5432"
            - name: POSTGRES_DB
              value: lago
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_USER
              value: lago
          image: postgres:14.0-alpine
          name: {{ .Release.Name }}-postgresql
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          # volumeMounts:
          #   - mountPath: /data/postgres
          #     name: lago-postgres-data
      restartPolicy: Always
      # volumes:
      #   - name: lago-postgres-data
      #     persistentVolumeClaim:
      #       claimName: lago-postgres-data
{{- end -}}
