apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.lago.service: {{ .Release.Name }}-front
  name: {{ .Release.Name}}-front-svc
spec:
  ports:
    - name: "80"
      port: {{ .Values.front.port | default 80 }}
      targetPort: 80
  selector:
    io.lago.service: {{ .Release.Name }}-front
