{{- if and .Values.global.ingress.enabled (hasKey .Values "LAGO_DOMAIN") (ne .Values.LAGO_DOMAIN "") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- if .Values.global.ingress.annotations }}
    {{- with .Values.global.ingress.annotations }}
      {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ .Values.LAGO_DOMAIN }}
    http:
      paths:
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-api-svc
            port:
              number: {{ .Values.api.service.port }}
  tls:
  - hosts:
      - {{ .Values.LAGO_DOMAIN }}
    secretName: {{ .Release.Name }}-ingress-secret
{{- end }}
