{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.lago.service: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis-svc
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.lago.service: {{ .Release.Name }}-redis
{{- end -}}
