apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: api
          image: redis:7.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              protocol: TCP
              name: "redis"
