apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-svc
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: {{ .Release.Name }}-redis
