apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "{{ .Release.Name }}-secrets") | default dict }}
  {{- $secretData := (get $secretObj "data" | default dict) }}
  {{- $rsaPrivateKey := (get $secretData "rsaPrivateKey") | default (genPrivateKey "rsa" | b64enc | b64enc)}}
  rsaPrivateKey: {{ $rsaPrivateKey | quote }}

  {{- if .Values.postgresql.enabled -}}}
  databaseUrl: 
  {{- end -}}