{{- if not .Values.global.s3.enabled and not .Values.minio.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.lago.service: {{ .Release.Name }}-storage-data
  name: {{ .Release.Name }}-storage-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.volumes.storage }}
{{- end -}}
