apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago-app.fullname" . }}
  labels:
    {{- include "lago-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lago-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lago-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lago-app.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ default .Chart.Name .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.container.command }}
          command: {{ toJson . }}
          {{- end }}
          {{- with .Values.container.args }}
          args: {{ toJson . }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: API_URL
              value: {{ .Values.config.apiUrl | required "config.apiUrl must be provided" }}
            - name: APP_ENV
              value: {{ .Values.config.env }}
            {{- with .Values.config.nangoKey }}
            - name: NANGO_PUBLIC_KEY
              value: {{ .Values.config.nangoKey }}
            {{- end }}
            {{- with .Values.config.signupEnabled }}
            - name: LAGO_DISABLE_SIGNUP
              value: {{ . | not | quote }}
            {{- end}}
            {{- with .Values.config.proxyUrl }}
            - name: LAGO_OAUTH_PROXY_URL
              value: {{ .Values.config.proxyUrl }}
            {{- end}}
            {{- with .Values.config.sentryDsn }}
            - name: SENTRY_DSN
              value: {{ .Values.config.sentryDsn }}
            {{- end}}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.container.ports.http }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
