apiVersion: v2
name: lago
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.9
appVersion: v1.41.2

dependencies:
  - name: lago-config
    alias: config
    version: 0.5.9
    repository: "file://../lago-config"
  - name: lago-rails
    alias: api
    version: 0.5.9
    repository: "file://../lago-rails"
  - name: lago-front
    alias: front
    version: 0.5.9
    repository: "file://../lago-front"
  - name: lago-rails
    alias: worker
    version: 0.5.9
    repository: "file://../lago-rails"
  - name: lago-rails
    alias: clock
    version: 0.5.9
    repository: "file://../lago-rails"
  - name: lago-rails
    alias: analytics-worker
    version: 0.5.9
    repository: "file://../lago-rails"
    condition: global.sidekiq.queues.analytics
  - name: lago-rails
    alias: billing-worker
    version: 0.5.9
    repository: "file://../lago-rails"
    condition: global.sidekiq.queues.billing
  - name: lago-rails
    alias: clock-worker
    version: 0.5.9
    repository: "file://../lago-rails"
    condition: global.sidekiq.queues.clock
  - name: lago-rails
    alias: events-worker
    version: 0.5.9
    repository: "file://../lago-rails"
    condition: global.sidekiq.queues.events
  - name: lago-rails
    alias: webhook-worker
    version: 0.5.9
    repository: "file://../lago-rails"
    condition: global.sidekiq.queues.webhook
  - name: lago-pdf
    alias: pdf
    version: 0.5.9
    repository: "file://../lago-pdf"
    condition: pdf.enabled
  - name: lago-rails
    alias: pdf-worker
    version: 0.5.9
    repository: "file://../lago-rails"
    condition: global.sidekiq.queues.pdf
  - name: lago-rails
    alias: events-consumer-worker
    version: 0.5.9
    repository: "file://../lago-rails"
    condition: global.streaming_ingestion.enabled
  - name: lago-events-processor-worker
    alias: events-processor-worker
    version: 0.5.9
    repository: "file://../lago-events-processor-worker"
    condition: global.streaming_ingestion.enabled

annotations:
  org.opencontainers.image.source: "https://github.com/getlago/lago-helm-charts"
