apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago.component.fullname" (dict "componentName" "front" "context" $) }}
  labels:
    {{- include "lago.component.labels" (dict "componentName" "front" "context" $) | nindent 4 }}
spec:
  {{- if not .Values.front.autoscaling.enabled }}
  replicas: {{ .Values.front.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lago.component.selectorLabels" (dict "componentName" "front" "context" $) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.front.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lago.component.labels" (dict "componentName" "front" "context" $) | nindent 8 }}
        {{- with .Values.front.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.front.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lago.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.front.podSecurityContext | nindent 8 }}
      containers:
        - name: front
          env:
            - name: API_URL
              value: {{ .Values.lagoConfig.api.url | quote }}
            - name: CODEGEN_API
              value: {{ .Values.lagoConfig.api.url | quote }}
            - name: APP_ENV
              value: production
            - name: LAGO_DISABLE_SIGNUP
              value: {{ not .Values.lagoConfig.signup.enabled | quote }}
            - name: SENTRY_DSN
              value: {{ .Values.lagoConfig.sentry.enabled | quote }}
          securityContext:
            {{- toYaml .Values.front.securityContext | nindent 12 }}
          image: "{{ .Values.front.image.repository }}:{{ .Values.front.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.front.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.front.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.front.resources | nindent 12 }}
          {{- with .Values.front.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.front.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.front.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.front.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.front.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
