# apiUrl: "api.lago.dev"
# frontUrl: "front.lago.dev"
apiUrl: "https://max-test-api.staging.getlago.com"   # Example: https://api.mydomain.dev
frontUrl: "https://max-test-app.staging.getlago.com"   # Example: https://app.mydomain.dev

global:
  databaseUrl: postgres://postgres:postgres@postgres:5432/postgres
  redisUrl: redis://redis:6379

  ingress:
    enabled: true
    frontHostname: max-test-app.staging.getlago.com
    apiHostname: max-test-api.staging.getlago.com
    className: nginx

  clickhouse:
    enabled: true
    port: 8123
    host: clickhouse
    ssl: false
    username: default
    password: default
    kafka:
      tls: false
      saslMechanisms: ""
      securityProtocol: ""
      bootstrapServers:
        - redpanda:9092

api:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"
worker:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

eventsConsumer:
  resources:
    requests:
      memory: '128Mi'
      cpu: "200m"

eventsProcessor:
  env: "development"
  resources:
    requests:
      memory: '128Mi'
      cpu: "200m"

eventsWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

clockWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

pdf:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

billingWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

pdfWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

webhookWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

paymentWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"
