{{- if not .Values.config.databaseAnalytical.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data-forecasted-usage.fullname" . }}-analytical-db
  labels:
    {{- include "lago-data-forecasted-usage.labels" . | nindent 4 }}
type: Opaque
data:
  databaseAnalytical.password: {{ b64enc .Values.config.databaseAnalytical.password }}
{{- end }}
