{{- if .Values.config.ml.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data-forecasted-usage.secretName" . }}
  labels:
    {{- include "lago-data-forecasted-usage.labels" . | nindent 4 }}
type: Opaque
data:
  ml.config: {{ required "config.ml.config value is required" .Values.config.ml.config | b64enc }}
{{- end }}
