{{- if not .Values.config.ml.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data-forecasted-usage.fullname" . }}-ml
  labels:
    {{- include "lago-data-forecasted-usage.labels" . | nindent 4 }}
type: Opaque
data:
  ml.config: {{ b64enc .Values.config.ml.config }}
{{- end }}
