{{- if .Values.config.s3.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data-forecasted-usage.s3.secretName" . }}
  labels:
    {{- include "lago-data-forecasted-usage.labels" . | nindent 4 }}
type: Opaque
data:
  s3.accessKeyId: {{ required "config.s3.accessKeyId value is required" .Values.config.s3.accessKeyId | b64enc }}
  s3.secretAccessKey: {{ required "config.s3.secretAccessKey value is required" .Values.config.s3.secretAccessKey | b64enc }}
{{- end }}
