{{- if not .Values.config.s3.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data-forecasted-usage.fullname" . }}-s3
  labels:
    {{- include "lago-data-forecasted-usage.labels" . | nindent 4 }}
type: Opaque
data:
  s3.accessKeyId: {{ b64enc .Values.config.s3.accessKeyId }}
  s3.secretAccessKey: {{ b64enc .Values.config.s3.secretAccessKey }}
{{- end }}
