{{- if .Values.config.s3.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lago-data-forecasted-usage.s3.secretName" . }}
  labels:
    {{- include "lago-data-forecasted-usage.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.config.s3.accessKeyId }}
  s3.accessKeyId: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.config.s3.secretAccessKey }}
  s3.secretAccessKey: {{ . | b64enc }}
  {{- end }}
{{- end }}
